name: Trigger static deployment
on:
  schedule:
    - cron: "5 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy static site
        run: curl --request GET --url ${{ secrets.VERCEL_DEPLOYMENT_URL }}
